final List<Map<String, dynamic>> exerciciosDisponiveis = [
  {'nome': 'Supino reto'},
  {'nome': 'Supino inclinado'},
  {'nome': 'Crucifixo reto'},
  {'nome': 'Desenvolvimento com barra'},
  {'nome': 'Elevação lateral'},
  {'nome': 'Agachamento livre'},
  {'nome': 'Leg press'},
  {'nome': 'Cadeira extensora'},
  {'nome': 'Mesa flexora'},
  {'nome': 'Stiff'},
  {'nome': 'Panturrilha em pé'},
  {'nome': 'Rosca direta'},
  {'nome': 'Rosca alternada'},
  {'nome': 'Tríceps corda'},
  {'nome': 'Tríceps francês'},
  {'nome': 'Puxada frente'},
  {'nome': 'Remada curvada'},
  {'nome': 'Abdominal supra'},
  {'nome': 'Prancha'},
  {'nome': 'Avanço'},
  {'nome': 'Cadeira abdutora'},
  {'nome': 'Cadeira adutora'},
  // ...adicione mais conforme desejar...
];
