final List<Map<String, dynamic>> alimentosDisponiveis = [
  {'nome': 'Ovo', 'proteina': 6, 'carbo': 0, 'gordura': 5},
  {'nome': 'Pão integral', 'proteina': 4, 'carbo': 20, 'gordura': 2},
  {'nome': 'Frango grelhado', 'proteina': 25, 'carbo': 0, 'gordura': 3},
  {'nome': 'Arroz', 'proteina': 2, 'carbo': 28, 'gordura': 0},
  {'nome': 'Banana', 'proteina': 1, 'carbo': 23, 'gordura': 0},
  {'nome': 'Iogurte', 'proteina': 5, 'carbo': 7, 'gordura': 3},
  {'nome': 'Batata doce', 'proteina': 2, 'carbo': 20, 'gordura': 0},
  {'nome': 'Carne moída', 'proteina': 26, 'carbo': 0, 'gordura': 15},
  {'nome': 'Peito de frango', 'proteina': 31, 'carbo': 0, 'gordura': 3},
  {'nome': 'Queijo branco', 'proteina': 7, 'carbo': 1, 'gordura': 6},
  {'nome': 'Aveia', 'proteina': 4, 'carbo': 14, 'gordura': 3},
  {'nome': 'Granola', 'proteina': 3, 'carbo': 17, 'gordura': 2},
  {'nome': 'Castanha de caju', 'proteina': 5, 'carbo': 9, 'gordura': 12},
  {'nome': 'Castanha-do-pará', 'proteina': 4, 'carbo': 4, 'gordura': 15},
  {'nome': 'Whey protein', 'proteina': 24, 'carbo': 3, 'gordura': 2},
  {'nome': 'Macarrão integral', 'proteina': 7, 'carbo': 38, 'gordura': 1},
  {'nome': 'Batata inglesa', 'proteina': 2, 'carbo': 17, 'gordura': 0},
  {'nome': 'Brócolis', 'proteina': 3, 'carbo': 6, 'gordura': 0},
  {'nome': 'Maçã', 'proteina': 0, 'carbo': 19, 'gordura': 0},
  {'nome': 'Pasta de amendoim', 'proteina': 4, 'carbo': 3, 'gordura': 8},
  {'nome': 'Iogurte grego', 'proteina': 10, 'carbo': 8, 'gordura': 6},
  {'nome': 'Suco de laranja', 'proteina': 1, 'carbo': 22, 'gordura': 0},
  {'nome': 'Tapioca', 'proteina': 1, 'carbo': 26, 'gordura': 0},
  {'nome': 'Ricota', 'proteina': 7, 'carbo': 1, 'gordura': 6},
  {'nome': 'Barra de proteína', 'proteina': 20, 'carbo': 18, 'gordura': 7},
  {'nome': 'Salmão', 'proteina': 25, 'carbo': 0, 'gordura': 14},
  {'nome': 'Atum', 'proteina': 23, 'carbo': 0, 'gordura': 1},
  {'nome': 'Tofu', 'proteina': 8, 'carbo': 2, 'gordura': 5},
  {'nome': 'Quinoa', 'proteina': 4, 'carbo': 21, 'gordura': 2},
  {'nome': 'Feijão preto', 'proteina': 9, 'carbo': 23, 'gordura': 0},
  {'nome': 'Lentilha', 'proteina': 9, 'carbo': 20, 'gordura': 0},
  {'nome': 'Grão-de-bico', 'proteina': 7, 'carbo': 27, 'gordura': 3},
  {'nome': 'Ervilha', 'proteina': 5, 'carbo': 14, 'gordura': 0},
  {'nome': 'Leite desnatado', 'proteina': 7, 'carbo': 10, 'gordura': 0},
  {'nome': 'Leite integral', 'proteina': 6, 'carbo': 9, 'gordura': 6},
  {'nome': 'Cenoura', 'proteina': 1, 'carbo': 10, 'gordura': 0},
  {'nome': 'Abobrinha', 'proteina': 1, 'carbo': 3, 'gordura': 0},
  {'nome': 'Abacate', 'proteina': 2, 'carbo': 8, 'gordura': 15},
  {'nome': 'Morango', 'proteina': 1, 'carbo': 8, 'gordura': 0},
  {'nome': 'Melancia', 'proteina': 1, 'carbo': 8, 'gordura': 0},
  {'nome': 'Pera', 'proteina': 0, 'carbo': 15, 'gordura': 0},
  {'nome': 'Uva', 'proteina': 0, 'carbo': 17, 'gordura': 0},
  {'nome': 'Peito de peru', 'proteina': 29, 'carbo': 0, 'gordura': 1},
  {'nome': 'Filé mignon', 'proteina': 28, 'carbo': 0, 'gordura': 8},
  {'nome': 'Costela bovina', 'proteina': 22, 'carbo': 0, 'gordura': 20},
  {'nome': 'Coxa de frango', 'proteina': 19, 'carbo': 0, 'gordura': 12},
  {'nome': 'Sardinha', 'proteina': 25, 'carbo': 0, 'gordura': 11},
  {'nome': 'Farinha de mandioca', 'proteina': 1, 'carbo': 24, 'gordura': 0},
  {'nome': 'Farinha de aveia', 'proteina': 4, 'carbo': 19, 'gordura': 2},
  {'nome': 'Mel', 'proteina': 0, 'carbo': 17, 'gordura': 0},
  {'nome': 'Azeite de oliva', 'proteina': 0, 'carbo': 0, 'gordura': 14},
  {'nome': 'Óleo de coco', 'proteina': 0, 'carbo': 0, 'gordura': 13},
  // ...adicione mais conforme desejar...
];
